fix #1013 カノニカルURLの出力を修正
baserproject/basercms pull request #1678
Opened 2021-04-08 21:21 UTC by yama

https://github.com/baserproject/basercms/issues/1013
上記の件について修正しました。確認をお願いします。

2021-04-12 08:46 UTC, ryuring requested changes

2021-04-12 08:46 UTC, ryuring commented on lib/Baser/View/Helper/BcBaserHelper.php
> +						$subSite
getContentsUrl() の第３引数は、サブドメインを使うかどうかの仕様ですので間違っています。
ここでは、サブサイトのURLを知らせることが仕様となっていますので、上の行にある
`$url = $subSite->makeUrl(new CakeRequest($pureUrl));` をそのまま利用してもよいと思います。

間違っているのは、rel属性で、`canonical` ではなく、`alternate` にして上げないといけないですね。

2021-04-12 08:52 UTC, ryuring requested changes
ざっとまとめました。

■ ２つのURLでアクセスできてしまう
http://localhost/sample
何も出さない

http://localhost/sample.html
正しいURLの canonicalを出力
```
<link rel="canonical" href="http://localhost/sample" />
```

■ PCとスマホのURLが別々で存在する
《PCの場合》
http://localhost/sample
スマホのURLのalternateを出力
```
<link rel="alternate" media="only screen and (max-width: 640px)" href="http://localhost/sp/sample" />
```

《スマホの場合》
http://localhost/sp/sample
PCのURLの canonicalを出力する
```
<link rel="canonical" href="http://localhost/sample" />
```

BcBaserHelper::afterRender() で上記の処理をうまいこと振り分けれるといいですね。

2021-04-12 08:52 UTC, ryuring commented on lib/Baser/View/Helper/BcBaserHelper.php
> +						$subSite
あ、第２引数の間違いですね。
第２引数は、フルURLにするかどうかですね。どちらにしても $subSite をあてがうのは間違ってます。

2021-04-13 03:32 UTC, yama commented
@ryuring 

ありがとうございます、調整してみます！

以下、余談ですが
fullフラグの処理を追ってみると、
BcBaser::getContentsUrl() → BcContents::getUrl() → BcContents::_Content->getUrl() というふうに
複数のメソッドに渡っていて、しかも末端のBcContents::_Content->getUrl()の粒度が大きめで、
コードを見ただけでは一瞬で内容を理解できませんでした。コメントが丁寧に書いてあるので
分かりますが、職人的なコーディングは結果的にはブラックボックス化してしまう気がします。
不具合が潜んでいても、誰もさわれないという・・
また、末端のBcContents::_Content->getUrl()を少し調整したい時に、他の部分で使ってないか
調べる必要があるので、ひと手間かかります。

メソッドのネストの解消と粒度の調整。今後はテストにも力を入れるということなので、
冪等性を意識する必要もあるのかなと思います。
今後の開発として、このへんを改善していけたらと思っています。

2021-04-13 03:35 UTC, yama commented
今回は$subSite->makeUrl(new CakeRequest($pureUrl));がそのまま使えそうですね、了解しました。

2021-04-13 05:17 UTC, yama commented
おっと、スマホでアクセスすると BcSmartphoneHelper.php を読みますね・・汗
難しくはないけど地味に複雑。

2021-04-13 07:25 UTC, yama commented
@ryuring 
`$subSite->makeUrl(new CakeRequest($pureUrl))` で思ったように値を取得できず調整を加えました。
確認をお願いします。

2021-05-09 03:21 UTC, merged

2021-05-09 03:22 UTC, ryuring commented
@yama ありがとうございました。
少し調整してテストを追加しました。
https://github.com/baserproject/basercms/commit/b9be736be009367992781c705857dea235f8be48