fix #1855 [CKEditor] aタグ内にブロック要素を置くと、勝手にaタグの外に吐き出される問題を解決
baserproject/basercms pull request #1856
Opened 2022-07-29 13:30 UTC by katokaisya

@ryuring 
@gondoh 

/app/Config/setting.phpで上書き可能な状態にしています。
ご確認の上、マージお願いできますでしょうか？

2022-08-01 02:18 UTC, ryuring commented on lib/Baser/View/Helper/BcCkeditorHelper.php
> +			$dtd = [
@katokaisya まずは、デフォルト値を、`lib/Baser/Config/setting.php` に記載お願いします。

2022-08-02 01:52 UTC, katokaisya commented
@ryuring 
調整しました。
ご確認お願いできますでしょうか？

2022-08-02 02:50 UTC, ryuring requested changes
@katokaisya レビュー完了しました。よろしくお願いします。

2022-08-02 02:50 UTC, ryuring commented on lib/Baser/View/Helper/BcCkeditorHelper.php
> +		/* CkEditorの自動整形のコントロール /app/Config/setting.phpで上書き可能 */
@katokaisya Configure を使っている時点で上書き可能なのはわかりますので不要かと

2022-08-02 02:50 UTC, ryuring commented on lib/Baser/View/Helper/BcCkeditorHelper.php
> +		if (isset($dtd['a']) && !empty($dtd['a'])) { // aタグ内に入れることを許可するブロック要素を出力
@katokaisya isset() は、!empty() でまかなえますので不要です。

2022-08-02 02:50 UTC, ryuring commented on lib/Baser/View/Helper/BcCkeditorHelper.php
> +		if (isset($dtd['removeEmpty']) && !empty($dtd['removeEmpty'])) { // 空を許可する要素を出力
@katokaisya 上記と同様

2022-08-03 02:07 UTC, ryuring requested changes
再レビュー入れてます。 @katokaisya

2022-08-03 02:07 UTC, ryuring commented on lib/Baser/Config/setting.php
> +		'AllowIntoA' => ['div', 'h1', 'h2', 'h3', 'h4', 'h5', 'dl', 'p'],
ロウワーキャメルケースでお願いします。 @katokaisya

2022-08-03 04:00 UTC, katokaisya commented
@ryuring 
ご指摘ありがとうございます。
ロウワーキャメルケースに変更しました。

2022-08-03 04:19 UTC, ryuring commented
@katokaisya ありがとうございます、マージしますね。

2022-08-03 04:19 UTC, merged

2022-08-04 01:16 UTC, katokaisya commented
@ryuring ありがとうございます。