「コンテンツフォルダーのコピー前・コピー後」のイベントを追加
baserproject/basercms pull request #2060
Opened 2023-04-19 01:52 UTC by HungDV2022

2023-04-25 05:38 UTC, ryuring requested changes

2023-04-25 05:38 UTC, ryuring commented on plugins/baser-core/src/Model/Table/ContentFoldersTable.php
> +    public function copy(int $id = null, $newParentId, $newTitle, $newSiteId= null)
$id をマストでお願いします。 @HungDV2022

2023-04-25 05:38 UTC, ryuring commented on plugins/baser-core/src/Model/Table/ContentFoldersTable.php
> +        $entity->content = new Content([
@HungDV2022 こちらを参考に変更をお願いします。

```php
$entity->content = new Content([
	'name' => $entity->content->name,
	'parent_id' => $newParentId,
	'title' => $newTitle,
	'author_id' => $newAuthorId,
	'site_id' => $newSiteId,
	'description' => $entity->content->description,
	'eyecatch' => $entity->content->eyecatch,
	'layout_template' => $entity->content->layout_tmplate?? ''
]);
```

2023-04-25 05:38 UTC, ryuring commented on plugins/baser-core/src/Model/Table/ContentFoldersTable.php
> +        } catch (PersistenceFailedException|\Throwable $e) {
@HungDV2022 そのままスローするのであれば、tryが不要です。

2023-04-26 03:11 UTC, HungDV2022 commented
@ryuring 
こちらのコメントを修正しました。確認お願いします。

2023-04-26 04:49 UTC, merged

2023-04-26 04:49 UTC, ryuring commented
@HungDV2022 ありがとうございます。マージしました。