「ブログタグの登録前・登録後・編集前・編集後」のイベントを追加
baserproject/basercms pull request #2064
Opened 2023-04-19 06:30 UTC by HungDV2022

2023-04-25 05:46 UTC, ryuring requested changes

2023-04-25 05:46 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/Admin/BlogTagsControllerTest.php
> +            $UploaderCategory = $event->getData('data');
細かいですが、変数は ロウワーキャメルでお願いします。 @HungDV2022

2023-04-25 05:46 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/Admin/BlogTagsControllerTest.php
> +            $UploaderCategory = $event->getData('data');
@HungDV2022 変数名がデタラメですね。UploaderCategory ではないです。

全体的に調整お願いします。

2023-04-26 03:34 UTC, HungDV2022 commented
@ryuring コメントの修正しました
確認お願いします。

2023-04-26 04:52 UTC, merged