fix #2073 Admin/BlogPostsController::add のユニットテスト実装
baserproject/basercms pull request #2075
Opened 2023-04-21 00:59 UTC by HungDV2022

2023-04-25 06:10 UTC, ryuring requested changes

2023-04-25 06:10 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Controller/Admin/PermissionGroupsControllerTest.php
> +        $this->PermissionGroupsController = new PermissionGroupsController($this->loginAdmin($this->getRequest()));
@HungDV2022 これ不要ですね

2023-04-25 06:11 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Controller/Admin/PermissionGroupsControllerTest.php
> +        $this->PermissionGroupsController = new PermissionGroupsController($this->loginAdmin($this->getRequest()));
これなんですかね、どのコミットにも入っている気がします。

2023-04-26 23:26 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/Controller/Admin/PermissionGroupsControllerTest.php
> +        $this->PermissionGroupsController = new PermissionGroupsController($this->loginAdmin($this->getRequest()));
@ryuring 
こちらはinitializeがあるコントローラーに参考しましたのでいつも$this->PermissionGroupsController変数がありました。
今度から注意します。

2023-04-27 05:34 UTC, merged