fix #2020 PagesService::createIndexConditions のユニットテスト実装
baserproject/basercms pull request #2095
Opened 2023-04-25 02:29 UTC by nghiem-mb

fix #2020 PagesService::createIndexConditions のユニットテスト実装

2023-04-25 06:27 UTC, ryuring requested changes

2023-04-25 06:27 UTC, ryuring commented on plugins/baser-core/src/Service/PagesService.php
> +    public function createIndexConditions(Query $query, $options = [])
@nghiem-mb テストをするために protected を public に変更するのはNGです。

2023-04-25 06:27 UTC, ryuring commented on plugins/baser-core/src/Service/PagesService.php
> +    public function createIndexConditions(Query $query, $options = [])
execPrivateMethod を利用してください。

2023-04-25 06:27 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Service/PagesServiceTest.php
> +        $pages = $this->Pages->find();
@nghiem-mb これは不要ですね。

2023-04-25 06:27 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Service/PagesServiceTest.php
> +        $result = $this->PagesService->createIndexConditions($query, $options)->all();
all() で、DBから取得結果を確認するでなく、createIndexConditionsで、$queryの値がどう変わったかというのがテスト内容になります。

$query->clause('where') で中身が取れるみたいですね。

@nghiem-mb

2023-04-25 10:05 UTC, nghiem-mb commented on plugins/baser-core/src/Service/PagesService.php
> +    public function createIndexConditions(Query $query, $options = [])
修正しました。
確認お願いします。

2023-04-26 05:06 UTC, ryuring commented
@nghiem-mb protected にアクセスするのに Closure を使うのはいいですが、「$queryの値がどう変わったかというのがテスト内容」というのが満たされていません。意味が伝わっていないのであれば質問してもらえると助かります。

2023-04-27 02:22 UTC, nghiem-mb commented
> @nghiem-mb protected にアクセスするのに Closure を使うのはいいですが、「$queryの値がどう変わったかというのがテスト内容」というのが満たされていません。意味が伝わっていないのであれば質問してもらえると助かります。

はい。
修正しました。
確認お願いします。

2023-04-27 05:57 UTC, merged