fix #2144 #2145 #2147 #2148 MailMessagesTable Unit test
baserproject/basercms pull request #2184
Opened 2023-05-16 04:18 UTC by nghiem-mb

fix #2144 #2145 #2147 #2148

2023-05-16 07:50 UTC, ryuring commented
@nghiem-mb こちらはまだ実装途中ですか？それともレビューに入っても大丈夫ですか？

2023-05-16 08:03 UTC, nghiem-mb commented
> @nghiem-mb こちらはまだ実装途中ですか？それともレビューに入っても大丈夫ですか？

はい。レビューお願いします。

2023-05-16 09:03 UTC, ryuring requested changes
@nghiem-mb レビューいれました。確認お願いします。

2023-05-16 09:03 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Model/MailMessagesTableTest.php
> +        $mail_message = new MailMessage(
@nghiem-mb 変数名はロウワーキャメルケースでお願いします。

2023-05-16 09:03 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Model/MailMessagesTableTest.php
> +        Closure::bind(
先日、プライベートメソッドのテストは、Closure でもいいと伝えましたが、読みにくいので、`$this->execPrivateMethod()` に変更して頂いてもいいですか？

2023-05-16 09:03 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Model/MailMessagesTableTest.php
> +            'created' => '2015-08-10 18:57:47',
@nghiem-mb 不要なフィールドは削ってください。

2023-05-16 09:03 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Model/MailMessagesTableTest.php
> +            'created' => '2015-08-10 18:57:47',
@nghiem-mb テストに不要なフィールドは削ってください。

2023-05-17 01:52 UTC, nghiem-mb commented
@ryuring 
修正しました。
確認お願いします。

2023-05-23 00:24 UTC, ryuring requested changes

2023-05-23 00:24 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Model/MailMessagesTableTest.php
> +        Closure::bind(
@nghiem-mb こちら改善されていないですね。

2023-05-23 00:24 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Model/MailMessagesTableTest.php
> +        $mail_message = new MailMessage(
こちら改善されていないですね。 @nghiem-mb

2023-05-23 00:27 UTC, ryuring commented
@nghiem-mb 再度レビューいれました。よろしくお願いしますー

2023-05-23 04:56 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Model/MailMessagesTableTest.php
> +        $mail_message = new MailMessage(
@nghiem-mb ロウワーキャメルケースはわかりますか？わからないのであれば質問してください。

```
$mail_message → $mailMessage
```

2023-05-23 04:57 UTC, ryuring commented
@nghiem-mb 再々レビューいれました。確認ください。

2023-05-23 05:52 UTC, nghiem-mb commented on plugins/bc-mail/tests/TestCase/Model/MailMessagesTableTest.php
> +        $mail_message = new MailMessage(
あー
関数名だと思っていました。
すみません。
修正します。

2023-05-23 08:10 UTC, nghiem-mb commented
> @nghiem-mb 再々レビューいれました。確認ください。

対応しました。
確認お願いします。

2023-05-26 09:20 UTC, merged