CustomTablesService::getList のユニットテストを実装
baserproject/basercms pull request #2563
Opened 2023-07-07 02:18 UTC by HungDV2022

2023-07-09 01:00 UTC, ryuring requested changes

2023-07-09 01:00 UTC, ryuring commented on plugins/bc-custom-content/tests/TestCase/Service/CustomTablesServiceTest.php
> +            'type' => 'recruit',
@HungDV2022 `type` には、1 か 2 が入る仕様です。`type` で絞り込むテストの追加をお願いします。

2023-07-10 04:18 UTC, HungDV2022 commented on plugins/bc-custom-content/tests/TestCase/Service/CustomTablesServiceTest.php
> +            'type' => 'recruit',
@ryuring ユニットテストを調整しました。確認お願いします。

2023-07-13 00:19 UTC, ryuring commented
@HungDV2022 ありがとうございます。マージします。

2023-07-13 00:21 UTC, merged