Test blog controller archives
baserproject/basercms pull request #2704
Opened 2023-08-24 10:20 UTC by nghiem-mb

2023-08-27 23:14 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/BlogControllerTest.php
> +        $controller->archives($blogFrontService, $blogContentsService, $blogPostsService, 'category');
@nghiem-mb `$this->get` を利用しない理由はありますか？

2023-08-29 08:59 UTC, nghiem-mb commented on plugins/bc-blog/tests/TestCase/Controller/BlogControllerTest.php
> +        $controller->archives($blogFrontService, $blogContentsService, $blogPostsService, 'category');
これだけ
$this->get('/bc-blog/blog/archives/category');
ダメみたいです。
なにか設定も必要か
ご指導お願いします。

2023-08-29 23:38 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/BlogControllerTest.php
> +        $controller->archives($blogFrontService, $blogContentsService, $blogPostsService, 'category');
@nghiem-mb ブログ機能は、コンテンツ管理のルーティングを利用しますので、通常のルーティングを想定したURLでは呼び出せません。

古いドキュメントですがこちらを確認ください。
https://baserproject.github.io/5/ucmitz/specification/baser-core/contents/contents_manager_api.html#URL%E3%81%AE%E6%B1%BA%E5%AE%9A

カテゴリーページのルーティングは、次の４つのテーブルの関連によりなりたちます。

- contents 
- blog_contents
- blog_posts
- blog_categories

例えば、次の条件の場合

- `contents` テーブルの `url` に、`/news/` と登録されている
- `blog_categories` テーブルの `name` に、`topics` と登録されている

その場合のURLは次のようになります。

```
/news/archives/category/topics
```

コードを見てたら、コメントにも書いてありますね
https://github.com/baserproject/basercms/blob/70b6bb6a6ffb81f5ed80f7c93f3b75d340ae79ef/plugins/bc-blog/src/Controller/BlogController.php#L162

2023-09-06 02:46 UTC, HungDV2022 commented on plugins/bc-blog/tests/TestCase/Controller/BlogControllerTest.php
> +        $controller->archives($blogFrontService, $blogContentsService, $blogPostsService, 'category');
@nghiem-mb 
下記のコードを参考してください。
 ```
　/**
     * test archives
     */
    public function test_archives()
    {
        //準備
        $this->enableSecurityToken();
        $this->enableCsrfToken();
        $this->loadFixtureScenario(InitAppScenario::class);
        $this->loadFixtureScenario(BlogTagsScenario::class);
        //正常系実行
        $this->get('/bc-blog/blog/archives/tag/tag1');
        $this->assertResponseOk();
    }
```

2023-09-14 01:46 UTC, ryuring requested changes

2023-09-14 01:46 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/BlogControllerTest.php
> +            'url' => '/index',
@nghiem-mb `url` を `/news/` にしてください。

2023-09-14 01:46 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/BlogControllerTest.php
> +        $this->get('/bc-blog/blog/archives/category/release');
@nghiem-mb contents テーブルによって、ルーティングが自動設定されますので、`/news/archives/category/release` でリクエストしてください。

以下のテストも同様に調整してください。

ちなみに、contents テーブルによるルーティングは、`/plugins/baser-core/src/Routing/Route/BcContentsRoute.php` で設定されています。

2023-09-15 04:19 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/BlogControllerTest.php
> +            'url' => '/news',
@nghiem-mb 実際の仕様では、BlogContentの場合、最後にスラッシュが入ります。
`/news/` としてください。

2023-09-15 04:49 UTC, merged