fix #2403 アップロードファイルのAPIについてフルパスを取得する仕組み
baserproject/basercms pull request #2771
Opened 2023-09-28 02:36 UTC by HungDV2022

2023-09-28 03:05 UTC, HungDV2022 commented
@ryuring 
何回もRe-testを実行しましたが、テストがFailedですが、原因がわかりますでしょうか。

2023-09-28 04:01 UTC, ryuring commented
@HungDV2022 インストールのコマンドが失敗しているようですので確認してみてくださいー

2023-09-28 07:19 UTC, ryuring commented on plugins/bc-blog/src/Model/Entity/BlogPost.php
> +    protected $_virtual = ['_eyecatch'];
ヘッダーコメントを付けてください @HungDV2022

2023-09-28 07:20 UTC, ryuring requested changes

2023-09-28 07:20 UTC, ryuring commented on plugins/baser-core/src/Utility/BcFileUploader.php
> +
@HungDV2022 戻り値の型定義が string になっていますが大丈夫でしょうか？

2023-09-29 02:41 UTC, HungDV2022 commented on plugins/bc-blog/src/Model/Entity/BlogPost.php
> +    protected $_virtual = ['_eyecatch'];
@ryuring 
こちらを変更しました。確認お願いします。

2023-09-29 02:43 UTC, HungDV2022 commented on plugins/baser-core/src/Utility/BcFileUploader.php
> +
こちらを変更しました。確認お願いします。

2023-09-29 02:44 UTC, HungDV2022 commented on plugins/bc-blog/src/Model/Entity/BlogPost.php
> +    protected $_virtual = ['_eyecatch'];
_get_eyecatchがユニットテストも追加しました。

2023-09-29 03:44 UTC, merged

2023-09-29 03:44 UTC, ryuring commented
@HungDV2022 ありがとうございました！