fix #1903 コンテンツ一覧（表）コピーの際にコピー先のタイトルに「のコピー」とつかない
baserproject/basercms pull request #2779
Opened 2023-10-03 01:50 UTC by HungDV2022

2023-10-04 00:15 UTC, ryuring commented
@HungDV2022 

コンテンツ管理での処理には矛盾があり、だから今回の問題になっていると思います。

- ツリーの場合：Javascript側で「のコピー」の文字が付与される
- テーブルの場合：付与されていない

ただ、コピーの仕様について、コンテンツ管理で管理されているエンティティ以外のエンティティについてどういう処理になっているか調べたところ、基本的にはテーブルで処理されていました。

https://github.com/baserproject/basercms/blob/68c90e6821176f55ce067df3c6a9dfd7cb0e4192/plugins/bc-mail/src/Model/Table/MailFieldsTable.php#L259
https://github.com/baserproject/basercms/blob/68c90e6821176f55ce067df3c6a9dfd7cb0e4192/plugins/bc-blog/src/Model/Table/BlogPostsTable.php#L660

コピーの仕様としてはこちらの方が正しいと思います。
こちらの仕様だとAPIでコピーした際も出来上がったデータがコピーだと分かります。

また、今回、formタグの中を変更する修正となっていますが、このformタグが将来的にコピー以外にも利用される可能性があるため、こちらの変更は望ましくありません。

その上で考慮した結果、新しい名前の指定がある場合には、そのタイトルを利用し、ない場合には「_copy」を付与する仕様にして欲しいです。

このようにする場合、以下のテーブルの変更が必要となるため、修正が大変ですが、よろしくお願いします。

- PagesTable
- MailContentsTable
- BlogContentsTable
- CustomContentsTable
- ContentFoldersTable
- ContentLinksTable

2023-10-04 00:18 UTC, ryuring commented
@HungDV2022 ちなみに、「新しい名前の指定がある場合には、そのタイトルを利用し、ない場合には「_copy」を付与する仕様」にするのは、コンテンツ管理で管理するエンティティだけで大丈夫です。BlogPosts や、MailFields は今回対象外にしてください。

2023-10-04 06:17 UTC, HungDV2022 commented
@ryuring 

CustomContentsTable以外は修正しました。

CustomContentsTableはコピー機能がないので対応しないです。
確認お願いします。

2023-10-04 06:20 UTC, ryuring requested changes

2023-10-04 06:20 UTC, ryuring commented on plugins/bc-admin-third/templates/Admin/element/Contents/index_row_table.php
> +      <input type="hidden" name="title" value="<?= h($content->title.' のコピー') ?>">
@HungDV2022 こちらは元に戻してください。

2023-10-04 08:18 UTC, HungDV2022 commented on plugins/bc-admin-third/templates/Admin/element/Contents/index_row_table.php
> +      <input type="hidden" name="title" value="<?= h($content->title.' のコピー') ?>">
@ryuring もっとに戻ったらタイトルに「のコピー」を付けなくてもいいですか。

2023-10-05 01:41 UTC, ryuring commented on plugins/bc-admin-third/templates/Admin/element/Contents/index_row_table.php
> +      <input type="hidden" name="title" value="<?= h($content->title.' のコピー') ?>">
@HungDV2022 

> また、今回、formタグの中を変更する修正となっていますが、このformタグが将来的にコピー以外にも利用される可能性があるため、こちらの変更は望ましくありません。
> その上で考慮した結果、新しい名前の指定がある場合には、そのタイトルを利用し、ない場合には「_copy」を付与する仕様にして欲しいです。

こちらに記載しているとおり、テーブル側で付ける仕様を想定しています。

2023-10-05 06:15 UTC, HungDV2022 commented on plugins/bc-admin-third/templates/Admin/element/Contents/index_row_table.php
> +      <input type="hidden" name="title" value="<?= h($content->title.' のコピー') ?>">
こちらを修正しました。確認お願いします。 @ryuring

2023-10-05 23:20 UTC, ryuring commented on plugins/bc-admin-third/templates/Admin/element/Contents/index_setup_tree.php
> +  'bcTreeCopyTitle' => __d('baser_core', '%s'),
@HungDV2022 この行はどこでも使われていないのであれば削除してください。

2023-10-05 23:21 UTC, ryuring commented on plugins/bc-admin-third/templates/Admin/element/Contents/index_setup_tree.php
> +  'bcTreeCopyTitle' => __d('baser_core', '%s'),
@HungDV2022 javascript側も調整お願いします。

2023-10-06 01:09 UTC, HungDV2022 commented on plugins/bc-admin-third/templates/Admin/element/Contents/index_setup_tree.php
> +  'bcTreeCopyTitle' => __d('baser_core', '%s'),
@HungDV2022 この行を削除しました。
JS側はこちらに調整しました。
plugins/bc-admin-third/src/js/admin/_lib/jquery.bcTree.js
確認お願いします。

2023-10-09 21:48 UTC, ryuring commented
@HungDV2022 ありがとうございました。マージしますね。

2023-10-09 21:48 UTC, merged