Dev #2773 bc plugin
baserproject/basercms pull request #2797
Opened 2023-10-11 01:25 UTC by nghiem-mb

2023-10-16 01:28 UTC, ryuring commented on plugins/baser-core/src/Utility/BcFolder.php
> +    public function move($source, $dest): bool
@nghiem-mb コメントヘッダーの追加をお願いします

2023-10-16 01:28 UTC, ryuring requested changes

2023-10-16 01:28 UTC, ryuring commented on plugins/baser-core/src/Utility/BcFolder.php
> +    public function copy($source, $dest): bool
@nghiem-mb コメントヘッダーの追加をお願いします。

2023-10-17 21:09 UTC, nghiem-mb commented on plugins/baser-core/src/Utility/BcFolder.php
> +    public function move($source, $dest): bool
コメントヘッダーも単体テストも追加しました。
確認お願いします。

2023-10-19 08:03 UTC, merged