BcMailを全体テストの実行対象に追加する
baserproject/basercms pull request #2835
Opened 2023-10-31 03:02 UTC by HungDV2022

2023-11-07 21:52 UTC, ryuring requested changes
@HungDV2022 レビュー入れました。確認お願いします。

2023-11-07 21:52 UTC, ryuring commented on plugins/bc-mail/tests/Scenario/MailContentsScenario.php
> +            'parent_id' => 0,
@HungDV2022 仕様上、`parent_id` が 0 になることはないのですが、そうしないとテストが通りませんか？

2023-11-07 21:52 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Controller/Api/Admin/MailContentsControllerTest.php
> +                'parent_id' => 0
@HungDV2022 仕様上、`parent_id` が 0 になることはないのですが、そうしないとテストが通りませんか？

2023-11-07 21:52 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Controller/Api/MailContentsControllerTest.php
> +        $this->assertResponseCode(403);
@HungDV2022 これは仕様が違います。

2023-11-07 21:52 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Controller/Api/Admin/MailMessagesControllerTest.php
> +        $this->assertResponseCode(500);
@HungDV2022 なぜ、ステータスコードが変わったのでしょう？原因が知りたいです。

2023-11-07 21:52 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Service/Admin/MailMessagesAdminServiceTest.php
> +        $mailMessageTable = TableRegistry::getTableLocator()->get('mail_message_1');
@HungDV2022 この取得方法でなければなりませんか？

2023-11-08 13:53 UTC, HungDV2022 commented on plugins/bc-mail/tests/Scenario/MailContentsScenario.php
> +            'parent_id' => 0,
@ryuring こちらを修正しました。確認お願いします。

2023-11-08 13:53 UTC, HungDV2022 commented on plugins/bc-mail/tests/TestCase/Controller/Api/Admin/MailContentsControllerTest.php
> +                'parent_id' => 0
@ryuring こちらを修正しました。確認お願いします。

2023-11-08 13:56 UTC, HungDV2022 commented on plugins/bc-mail/tests/TestCase/Controller/Api/Admin/MailMessagesControllerTest.php
> +        $this->assertResponseCode(500);
<img width="871" alt="スクリーンショット 2023-11-08 20 55 04" src="https://github.com/baserproject/basercms/assets/110375578/ca6de1bf-47e0-4df5-a8a1-0c88e9941042">
@ryuring コードを見ると$queryParams['status']があれば403を返します。
確認お願いします。

2023-11-08 14:07 UTC, HungDV2022 commented on plugins/bc-mail/tests/TestCase/Service/Admin/MailMessagesAdminServiceTest.php
> +        $mailMessageTable = TableRegistry::getTableLocator()->get('mail_message_1');
@ryuring 
動的なテーブルなのでFactoryとか取得でいないです。

2023-11-09 00:01 UTC, HungDV2022 commented on plugins/bc-mail/tests/TestCase/Controller/Api/MailContentsControllerTest.php
> +        $this->assertResponseCode(403);
@ryuring コードを見ると$queryParams['status']があれば403を返します。 確認お願いします。
![image](https://github.com/baserproject/basercms/assets/110375578/ef8ac853-6cf4-49aa-bcca-a2bafd1955c8)

2023-11-09 00:16 UTC, HungDV2022 commented on plugins/bc-mail/tests/TestCase/Controller/Api/Admin/MailMessagesControllerTest.php
> +        $this->assertResponseCode(500);
<img width="1439" alt="スクリーンショット 2023-11-09 7 15 51" src="https://github.com/baserproject/basercms/assets/110375578/a82b7031-bd00-40de-887b-1256a9917797">
@ryuring 
以前に本家コードがステータスコードを変わりましたので。

2023-11-09 10:25 UTC, HungDV2022 commented on plugins/bc-mail/tests/TestCase/Controller/Api/Admin/MailContentsControllerTest.php
> +                'parent_id' => 0
@ryuring こちらのところはNULLを変更しました、確認お願いします。

2023-11-15 09:25 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Service/Admin/MailMessagesAdminServiceTest.php
> +        $mailMessageTable = TableRegistry::getTableLocator()->get('mail_message_1');
@HungDV2022 なるほど、了解しました。

2023-11-15 09:25 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Controller/Api/Admin/MailMessagesControllerTest.php
> +        $this->assertResponseCode(500);
@HungDV2022 なるほど、了解しました。

2023-11-15 09:25 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Controller/Api/MailContentsControllerTest.php
> +        $this->assertResponseCode(403);
@HungDV2022 コメントに「ログインしている状態では status パラメーターへへのアクセできるか確認」と書いてるのが間違いのようですね。このAPIは、ログインしているかどうかを判定していないですね。

2023-11-15 09:26 UTC, merged