BcUploaderを全体テストの実行対象に追加する
baserproject/basercms pull request #2838
Opened 2023-10-31 04:50 UTC by HungDV2022

2023-11-07 21:57 UTC, ryuring requested changes
@HungDV2022 レビューいれました。確認お願いします。

2023-11-07 21:57 UTC, ryuring commented on plugins/bc-theme-file/tests/TestCase/Controller/Admin/ThemeFilesControllerTest.php
> -        $this->post('/baser/admin/bc-theme-file/theme_files/index/BcThemeSample/layout3');
@HungDV2022 削除した理由はなんでしょうか？

2023-11-07 21:57 UTC, ryuring commented on plugins/bc-uploader/tests/TestCase/Service/UploadFilesServiceTest.php
> -        //異常系実行
@HungDV2022 削除した理由はなんですか？

2023-11-07 21:57 UTC, ryuring commented on plugins/bc-uploader/tests/TestCase/Service/UploadFilesServiceTest.php
> -        //正常系実行
@HungDV2022 削除した理由はなんですか？

2023-11-07 21:57 UTC, ryuring commented on plugins/bc-uploader/tests/TestCase/Service/UploadFilesServiceTest.php
> -        $this->assertFalse($result);
@HungDV2022 仕様が変わってしまっています。理由はなんですか？

2023-11-08 00:08 UTC, HungDV2022 commented on plugins/bc-theme-file/tests/TestCase/Controller/Admin/ThemeFilesControllerTest.php
> -        $this->post('/baser/admin/bc-theme-file/theme_files/index/BcThemeSample/layout3');
@ryuring 
こちらと同じ理由です。https://github.com/baserproject/basercms/pull/2844#discussion_r1385780378

2023-11-08 00:27 UTC, HungDV2022 commented on plugins/bc-uploader/tests/TestCase/Service/UploadFilesServiceTest.php
> -        //異常系実行
@ryuring 同じメソッドで正常系テスト異常系テストが実装できないので別メソッドを書きました。確認お願いします

2023-11-08 00:31 UTC, HungDV2022 commented on plugins/bc-uploader/tests/TestCase/Service/UploadFilesServiceTest.php
> -        //正常系実行
@ryuring 
ログインしているテストとログインしないテストは同じメソッドで実行できないので別メソッドを書こうと思いました。
でもこちらメソッドはローカル環境で問題ないですが、Git環境だとエラーになりましたので「` $this->markTestIncomplete('こちらのテストはまだ未確認です');`」を追加しました。

2023-11-08 00:35 UTC, HungDV2022 commented on plugins/bc-uploader/tests/TestCase/Service/UploadFilesServiceTest.php
> -        $this->assertFalse($result);
@ryuring https://github.com/baserproject/basercms/pull/2838/files/efba8b5317f3410f13d2ea06da78f2f74e51c578#r1385795775
こちらと同じ理由でメソッドを分けてテスト方がいいだと思います。同じメソッドを書くと期待値が変わります。

2023-11-09 06:00 UTC, ryuring commented on plugins/bc-theme-file/tests/TestCase/Controller/Admin/ThemeFilesControllerTest.php
> -        $this->post('/baser/admin/bc-theme-file/theme_files/index/BcThemeSample/layout3');
了解しました。

2023-11-09 10:39 UTC, HungDV2022 commented on plugins/bc-uploader/tests/TestCase/Service/UploadFilesServiceTest.php
> -        //異常系実行
@ryuring 
Git環境だとisEditableメソッドをテストした時いつもTrueを変えしますので異常系をテストできないです。一旦コメントアウトしました。
確認お願いします。

2023-11-15 09:27 UTC, merged