ユニットテスト調整
baserproject/basercms pull request #3003
Opened 2024-01-04 03:27 UTC by HungDV2022

2024-01-04 07:44 UTC, ryuring requested changes

2024-01-04 07:44 UTC, ryuring commented on plugins/baser-core/src/Database/Schema/BcSchema.php
> +                //!$connection->supportsDynamicConstraints() cakephp5をサポートしないから削除します。
@HungDV2022 コメントは削除してしまっていいです

2024-01-04 07:44 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Controller/Component/BcAdminContentsComponentTest.php
> +        $this->assertNotNull($listeners[0]);
@HungDV2022 `$listeners[0]` には何が入ってますか？

2024-01-05 02:50 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/Controller/Component/BcAdminContentsComponentTest.php
> +        $this->assertNotNull($listeners[0]);
<img width="859" alt="スクリーンショット 2024-01-05 9 22 51" src="https://github.com/baserproject/basercms/assets/110375578/bee02f9f-f553-4a44-ac27-3b3d64351921">
@ryuring 画像のように値が入っていますが、
$listeners[0] ->callableを書くとNULLを返しました。
取得方法をわからないですから$listeners[0]を確認しました。

2024-01-05 02:50 UTC, HungDV2022 commented on plugins/baser-core/src/Database/Schema/BcSchema.php
> +                //!$connection->supportsDynamicConstraints() cakephp5をサポートしないから削除します。
@ryuring コメントを削除しました。確認お願いします。

2024-01-05 05:10 UTC, merged