fix #3010 [baserCMS5系]サブサイトのドメイン設定ができない問題を解決
baserproject/basercms pull request #3011
Opened 2024-01-05 09:47 UTC by katokaisya

@ryuring 
お手数ですが、ご確認お願いできますでしょうか？
（package-lock.json以外は全てコミットしていますが、不要であれば、ご指摘ください。）

2024-01-06 08:16 UTC, ryuring requested changes

2024-01-06 08:16 UTC, ryuring commented on plugins/bc-admin-third/src/js/admin/sites/form.js
> +        console.log(use_subdomain);
@katokaisya 変数名はロウワーキャメルケースでお願いします

2024-01-06 08:16 UTC, ryuring commented on plugins/bc-admin-third/src/js/admin/sites/form.js
> +        console.log(use_subdomain);
console.logは削除お願いします

2024-01-06 08:16 UTC, ryuring commented on plugins/bc-admin-third/src/js/admin/sites/form.js
> +    function chengeUseDomein(use_subdomain) {
@katokaisya ドメインの綴は、Domain です。

2024-01-06 08:16 UTC, ryuring commented on plugins/bc-admin-third/src/js/admin/sites/form.js
> +        use_subdomain = $("input[name='use_subdomain']:checked").val();
@katokaisya chengeUseDomein() 内で既に、DOMを参照する仕様となってますので、`$("input[name='use_subdomain']:checked").val()` も引き数にせず、関数内で直接参照してしまっていいと思います。そうすると処理がかなりスッキリするかと。

2024-01-06 08:16 UTC, ryuring commented on plugins/bc-admin-third/templates/Admin/element/Sites/form.php
> +      <th class="bca-form-table__label"><?php echo $this->BcAdminForm->label('use_subdomain', __d('baser_core', 'ドメイン（サブドメイン）利用')) ?></th>
@katokaisya `外部ドメイン利用` に変更お願いします。

2024-01-06 08:16 UTC, ryuring commented on plugins/bc-admin-third/templates/Admin/element/Sites/form.php
> +    <tr class="domain_type">
@katokaisya DOM操作で一意であるべき対象であれば、id にしましょう。
また、idは、アッパーキャメルケースでお願いします。（baser内で完全には統一できてませんが、、、）

2024-01-12 15:52 UTC, katokaisya commented
@ryuring 
レビューありがとうございます。

> ・変数名はロウワーキャメルケースでお願いします
> ・console.logは削除お願いします
> ・ドメインの綴は、Domain です。
> ・chengeUseDomein() 内で既に、DOMを参照する仕様となってますので、$("input[name='use_subdomain']:checked").val() も引き数にせず、関数内で直接参照してしまっていいと思います。そうすると処理がかなりスッキリするかと。
> ・外部ドメイン利用 に変更お願いします。
> ・DOM操作で一意であるべき対象であれば、id にしましょう。また、idは、アッパーキャメルケースでお願いします。

こちら対応しましたので、お手数ですが、ご確認お願いできますでしょうか？

2024-01-14 10:50 UTC, ryuring commented on plugins/bc-admin-third/src/js/admin/sites/form.js
> +    function chengeUseDomein(use_subdomain) {
@katokaisya こちら解消できてないみたいです。メソッド名のところです。

2024-01-14 10:51 UTC, ryuring commented on plugins/bc-admin-third/src/js/admin/sites/form.js
> +        use_subdomain = $("input[name='use_subdomain']:checked").val();
@katokaisya こちら解消できていないです。意味が伝わりにくかったら連絡ください。

2024-01-14 10:53 UTC, ryuring commented on plugins/bc-admin-third/templates/Admin/element/Sites/form.php
> +      <th class="bca-form-table__label"><?php echo $this->BcAdminForm->label('use_subdomain', __d('baser_core', 'ドメイン（サブドメイン）利用')) ?></th>
@katokaisya サブドメインも含めて外部ドメインと呼べるので、テーブル見出しは「外部ドメイン」として、ヘルプで、サブドメインも含めることを記述した方がスッキリするかと思いますがいかがでしょう？

2024-01-14 10:53 UTC, ryuring commented
@katokaisya 再度レビュー入れましたので確認よろしくお願いします。

2024-01-19 04:46 UTC, ryuring commented on plugins/bc-admin-third/src/js/admin/sites/form.js
> +    $("input[name='use_subdomain']").click(function() {
@katokaisya こちらはこのコードでいけます。

```javascript
$("input[name='use_subdomain']").click('chengeUseDomain');
```

2024-02-02 10:44 UTC, katokaisya commented
@ryuring 
返信遅れましてすみません。
対応しています。
ご確認お願いできますでしょうか？

2024-02-03 08:07 UTC, ryuring commented on plugins/bc-admin-third/templates/Admin/element/Sites/form.php
> +      <th class="bca-form-table__label"><?php echo $this->BcAdminForm->label('use_subdomain', __d('baser_core', 'ドメイン（サブドメイン）利用')) ?></th>
@katokaisya こちらが解消できてないですね。

2024-02-17 03:06 UTC, ryuring commented
@katokaisya 一箇所対応できていないのでこちらで修正しますね。

2024-02-17 03:07 UTC, merged