Dev cake5 adjust fix unitest
baserproject/basercms pull request #3013
Opened 2024-01-06 05:16 UTC by HungDV2022

2024-01-06 08:30 UTC, ryuring requested changes
@HungDV2022 レビューを入れておきました。

2024-01-06 08:30 UTC, ryuring commented on plugins/bc-custom-content/src/Controller/Api/Admin/CustomFieldsController.php
> +            'customFields' =>  $service->getIndex()
@HungDV2022 `paginate` を外すと仕様が変わってしまいますが、外さないと対応できませんか？

2024-01-06 08:30 UTC, ryuring commented on plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
> +        foreach ($blogPosts as $item) {
@HungDV2022 `each()` は無くなってしまいましたか？

2024-01-06 08:30 UTC, ryuring commented on plugins/bc-custom-content/tests/TestCase/Controller/Admin/CustomFieldsControllerTest.php
> +        $this->assertResponseCode(500);
@HungDV2022 200から500に変わっているのは別の問題ではないでしょうか？入力エラーで500はありえないと思います。

2024-01-06 08:30 UTC, ryuring commented on plugins/bc-custom-content/tests/TestCase/Controller/Admin/CustomFieldsControllerTest.php
> +        $this->assertResponseCode(500);
@HungDV2022 こちらも200から500というのは別の問題ではないでしょうか？

2024-01-06 08:30 UTC, ryuring commented on plugins/bc-theme-file/src/Service/ThemeFilesService.php
> +            copy($tmpName, $filePath);
@HungDV2022 renameでは駄目ですか？ファイルが残ってしまうのでは？

2024-01-06 08:30 UTC, ryuring commented on plugins/bc-theme-file/src/Service/ThemeFilesService.php
> +            move_uploaded_file($tmpName, $filePath);
@HungDV2022 `UploadedFile` を利用する前提であれば、`UploadedFile::moveTo()` を利用してみましょうか。

2024-01-06 08:30 UTC, ryuring commented on plugins/bc-theme-file/tests/TestCase/Controller/Api/Admin/ThemeFilesControllerTest.php
> +        unlink($fullpath . 'new_folder/uploadTestFile.html');
@HungDV2022 unlinkだと、new_folderが残ってしまうのではないでしょうか？

2024-01-09 02:24 UTC, HungDV2022 commented on plugins/bc-custom-content/src/Controller/Api/Admin/CustomFieldsController.php
> +            'customFields' =>  $service->getIndex()
@ryuring 
CustomFieldsTable.php::findAll()のメソッドに問題でした。
確認お願いします。

2024-01-09 02:31 UTC, HungDV2022 commented on plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
> +        foreach ($blogPosts as $item) {
@ryuring 
はい、each()が使えなくなりました。別方法を対応しました。確認お願いします。

2024-01-09 02:34 UTC, HungDV2022 commented on plugins/bc-custom-content/tests/TestCase/Controller/Admin/CustomFieldsControllerTest.php
> +        $this->assertResponseCode(500);
@ryuring BcAdminAppView.phpにBcCcRelatedHelpeが存在しないから
plugins/bc-custom-content/plugins/BcCcRelated/templates/Admin/element/custom_field_meta.php
こちらでは$this->BcCcRelated->getTableList()が使えないでした。
確認お願いします。

2024-01-09 02:34 UTC, HungDV2022 commented on plugins/bc-custom-content/tests/TestCase/Controller/Admin/CustomFieldsControllerTest.php
> +        $this->assertResponseCode(500);
@ryuring 
https://github.com/baserproject/basercms/pull/3013#discussion_r1445565676
と同じ原因でした。

2024-01-09 02:43 UTC, HungDV2022 commented on plugins/bc-theme-file/src/Service/ThemeFilesService.php
> +            copy($tmpName, $filePath);
@ryuring UploadedFile::moveTo()に変更しました。確認お願いします。

2024-01-09 02:43 UTC, HungDV2022 commented on plugins/bc-theme-file/src/Service/ThemeFilesService.php
> +            move_uploaded_file($tmpName, $filePath);
@ryuring UploadedFile::moveTo()に変更しました。確認お願いします。

2024-01-09 02:44 UTC, HungDV2022 commented on plugins/bc-theme-file/tests/TestCase/Controller/Api/Admin/ThemeFilesControllerTest.php
> +        unlink($fullpath . 'new_folder/uploadTestFile.html');
@ryuring こちらを調整しました。確認お願いします。

2024-01-09 21:18 UTC, ryuring requested changes

2024-01-09 21:18 UTC, ryuring commented on plugins/baser-core/src/View/BcAdminAppView.php
> +        $this->addHelper('BcCcRelated.BcCcRelated');
@HungDV2022 こちらは自動追加される仕様ですので、何故、自動追加されていないかを調べないといけないです。
わからなければ一旦、除外しておいてください。

2024-01-09 21:18 UTC, ryuring commented on plugins/bc-theme-file/src/Service/ThemeFilesService.php
> +        $postData['file']->moveTo($fullpath . DS . $name);
@HungDV2022 moveに失敗した場合の処理も書いて欲しいです

2024-01-09 21:21 UTC, ryuring commented on plugins/bc-custom-content/tests/TestCase/Controller/Admin/CustomFieldsControllerTest.php
> +        $this->assertResponseCode(500);
@HungDV2022 こちら別の問題の可能性があります。一旦、見送ってください。

2024-01-09 21:21 UTC, ryuring commented on plugins/bc-custom-content/tests/TestCase/Controller/Admin/CustomFieldsControllerTest.php
> +        $this->assertResponseCode(500);
@HungDV2022 こちらも一旦見送ってください。

2024-01-09 21:22 UTC, ryuring commented
@HungDV2022 再レビューいれました。確認お願いします。

2024-01-10 00:50 UTC, HungDV2022 commented on plugins/baser-core/src/View/BcAdminAppView.php
> +        $this->addHelper('BcCcRelated.BcCcRelated');
@ryuring 
こちらは調べましたが、原因を特定できなかったので除外しました。
確認お願いします。

2024-01-10 00:51 UTC, HungDV2022 commented on plugins/bc-theme-file/src/Service/ThemeFilesService.php
> +        $postData['file']->moveTo($fullpath . DS . $name);
@ryuring 
moveToメソッドは戻るちがないからTry・Catchを書きました。
確認お願いします。

2024-01-10 01:26 UTC, ryuring commented on plugins/baser-core/src/View/BcAdminAppView.php
> +        $this->addHelper('BcCcRelated.BcCcRelated');
@HungDV2022 了解しました。
CustomFieldsControllerTest::testEdit
CustomFieldsControllerTest::test_add
はこちらで確認しますね。

2024-01-10 01:27 UTC, ryuring commented on plugins/bc-theme-file/src/Service/ThemeFilesService.php
> +        $postData['file']->moveTo($fullpath . DS . $name);
@HungDV2022 
> moveToメソッドは戻るちがないから

そういうことなんですね。
では、例外が発生したらそのまま投げてもらった方がよいので、try catch は後で外しておいてください。
一旦、マージします。

2024-01-10 01:27 UTC, merged