Blog helper test categories
baserproject/basercms pull request #3029
Opened 2024-01-16 01:33 UTC by nghiem-mb

2024-01-16 02:05 UTC, nghiem-mb commented
@ryuring 
バグ確認お願いします。

2024-01-16 06:28 UTC, ryuring commented
一旦、担当を戻しておきますね @nghiem-mb

2024-01-17 04:53 UTC, ryuring requested changes

2024-01-17 04:53 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Model/BlogCategoriesTableTest.php
> +//        dd($result->toArray()[0]->children);
@nghiem-mb 削除必要

2024-01-17 04:53 UTC, ryuring commented on plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
> +        $query->matching('BlogPosts.BlogContents.Contents');
@nghiem-mb これは使い方が違う気がします。全ての条件において無理やり inner join で繋げることになり負荷が高くなるので、必要な時だけ使うように調整してください。

2024-01-17 04:56 UTC, nghiem-mb commented on plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
> +        $query->matching('BlogPosts.BlogContents.Contents');
はい。調整します。

2024-01-17 23:35 UTC, ryuring requested changes

2024-01-17 23:35 UTC, ryuring commented on plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
> +        if ($options['siteId'] !== false && !is_null($options['siteId'])) {
@nghiem-mb 238行目にまとめることはできませんか？

2024-01-18 02:25 UTC, ryuring commented on plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
> +        if ($options['siteId'] !== false && !is_null($options['siteId'])) {
@nghiem-mb 以前共有したこちらのコードを参考にお願いします。
```
            $query->matching('BlogPosts.BlogContents.Contents', function ($q) use ($params) {
                return $q->where(['Contents.site_id' => $params['siteId']]);
            });
```

2024-01-18 22:19 UTC, merged