BlogPostsService::getUrlのユニットテスト
baserproject/basercms pull request #3052
Opened 2024-01-19 05:42 UTC by HungDV2022

2024-01-29 03:44 UTC, ryuring requested changes

2024-01-29 03:44 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
> +        $rs = $this->BlogPostsService->getUrl(ContentFactory::get(100), BlogPostFactory::get(1), false);
@HungDV2022 第３引き数が true の場合のテストもお願いします。

2024-02-01 07:40 UTC, HungDV2022 commented on plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
> +        $rs = $this->BlogPostsService->getUrl(ContentFactory::get(100), BlogPostFactory::get(1), false);
@ryuring 第３引き数がtrueの場合、テストを追加しました。確認お願いします。

2024-02-01 09:18 UTC, ryuring commented
@HungDV2022 ありがとうございます！

2024-02-01 09:19 UTC, merged