fix #3050ユーティリティ機能にシンボリックリンク作成機能する問題を解決
baserproject/basercms pull request #3063
Opened 2024-01-22 09:12 UTC by katokaisya

@ryuring
こちら、調整を入れております。
お手数ですが、ご確認お願い申し上げます。
 
cc @kaburk

2024-01-23 00:36 UTC, ryuring commented on plugins/baser-core/src/BcPlugin.php
> +        if (exec($command)) return true;
第二引き数の判定の方が間違いないと思います。

```
exec($command, $out, $code);
return ($code === 0);
```

2024-01-23 00:43 UTC, ryuring requested changes
@katokaisya レビュー入れました。よろしくお願いします。

2024-01-23 00:43 UTC, ryuring commented on plugins/baser-core/src/Controller/Admin/UtilitiesController.php
> +            $this->BcMessage->setInfo(__d('baser_core', 'プラグインアセットのシンボリックリンクの作成に失敗しました。'), true);
失敗した場合は setError を利用してください

2024-01-23 00:43 UTC, ryuring commented on plugins/bc-admin-third/templates/Admin/Utilities/index.php
> +    <?php echo __d('baser_core', '別環境への移設などでテーマ・プラグインのwebrootフォルダ内のリンク切れが起こってしまった際に、シンボリックリンクを再作成します。') ?>
こちらに修正お願いします。
```
テーマ・プラグインのアセットファイルへのシンボリックリンクを再作成します。別環境への移設などで、テーマやプラグインの画像、CSS、Javascriptへのリンク切れが発生した際に利用します。
```

2024-01-23 00:43 UTC, ryuring commented on plugins/bc-admin-third/templates/Admin/Utilities/index.php
> +  <?php echo $this->BcAdminForm->postLink(__d('baser_core', 'テーマへのシンボリックリンクを再作成'),
`シンボリックリンクを再作成する` でお願いします。

2024-01-23 00:43 UTC, ryuring commented on plugins/bc-admin-third/templates/Admin/Utilities/index.php
> +      'confirm' => __d('baser_core', 'テーマへのシンボリックリンクを再作成します。いいですか？')
`テーマ・プラグインへのシンボリックリンクを再作成します。本当によろしいですか？` でお願いします。

2024-01-23 01:41 UTC, katokaisya commented
@ryuring 
レビューありがとうございます。
修正しました。

2024-01-31 22:44 UTC, ryuring commented
@katokaisya 全ての修正を確認しました。マージしますね。ありがとうございました。

2024-01-31 22:44 UTC, merged