testGetBlogTemplates
baserproject/basercms pull request #3067
Opened 2024-01-24 02:53 UTC by nghiem-mb

2024-01-29 03:57 UTC, ryuring requested changes

2024-01-29 03:57 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        $result = $this->Blog->getBlogTemplates(1);
@nghiem-mb `getBlogTempletes` の第一引き数 $siteId の初期値は、1に変更してください。
baserCMS4から、baserCMS５になるにあたり、site_id が 0 というのはなくなったためです。

2024-01-29 03:57 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        $this->expectException('Cake\Datasource\Exception\RecordNotFoundException');
@nghiem-mb ヘルパー呼び出しの際に、`RecordNotFoundException` が出てしまうのは良くないので、どこかで例外処理を書く必要があります。

2024-01-29 03:57 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +            ['nada-icons', ['Blog' => 'Blog','default' => 'default']]
@nghiem-mb 結果に、`'Blog' => 'Blog'` が入ってしまってはいけません。何が原因か調査してもらってもいいですか？

2024-02-14 04:32 UTC, closed without merging

2024-02-14 04:32 UTC, HungDV2022 commented
https://github.com/baserproject/basercms/pull/3113
こちらPRに修正しました。