BlogHelper::parseContentNameのユニットテスト
baserproject/basercms pull request #3071
Opened 2024-01-25 05:31 UTC by HungDV2022

2024-01-29 04:07 UTC, ryuring requested changes

2024-01-29 04:07 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        //戻る値を確認
@HungDV2022 日本語の学習のためお伝えしていくと、「戻り値」が正しいです。

2024-01-29 04:07 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        $this->assertTrue($rs['autoSetCurrentBlog']);
@HungDV2022 本体のメソッドで、`autoSetCurrentBlog` を unset() する処理を追加していてください。

2024-01-29 06:49 UTC, HungDV2022 commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        //戻る値を確認
@ryuring ありがとうございます。

2024-01-29 06:49 UTC, HungDV2022 commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        $this->assertTrue($rs['autoSetCurrentBlog']);
@ryuring autoSetCurrentBlogはTrue場合、テストを追加しました、確認お願いします。

2024-01-30 23:59 UTC, ryuring requested changes

2024-01-30 23:59 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        //戻る値を確認
@HungDV2022 戻る値のままになっているようです

2024-01-30 23:59 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        $this->assertTrue($rs['autoSetCurrentBlog']);
@HungDV2022 伝え方が悪かったですね。戻り値に、autoSetCurrentBlogが含まれてはいけないので、本体の処理で unset() する処理を追加してくださいということです。

2024-02-01 07:38 UTC, HungDV2022 commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        //戻る値を確認
@ryuring 
こちらを訂正しました。
確認お願いします。

2024-02-01 07:39 UTC, HungDV2022 commented on plugins/bc-blog/src/View/Helper/BlogHelper.php
> +        unset($options['autoSetCurrentBlog']);
@ryuring こちらにunsetを追加しますでしょうかね。
確認お願いします。

2024-02-01 09:17 UTC, ryuring commented on plugins/bc-blog/src/View/Helper/BlogHelper.php
> +        unset($options['autoSetCurrentBlog']);
@HungDV2022 そういうことですー

2024-02-01 09:18 UTC, merged