BlogHelper::getBlogTemplates のユニットテスト
baserproject/basercms pull request #3113
Opened 2024-02-14 04:32 UTC by HungDV2022

2024-02-15 22:40 UTC, ryuring requested changes

2024-02-15 22:40 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        SiteConfigFactory::make([
@HungDV2022 テーマは、SiteConfigFactory ではなく、Site に保存するようになりました、SiteConfigFactoryは不要です。

2024-02-15 22:41 UTC, ryuring commented
@HungDV2022 テーマ `nada-icons` は廃止になりました。 `BcThemeSample` でテストをお願いします。
おそらく、`Blog` が追加されてしまう問題は解消します。

2024-02-16 10:30 UTC, HungDV2022 commented on plugins/bc-theme-file/tests/TestCase/Service/Admin/ThemeFilesAdminServiceTest.php
> +        $this->assertCount(11, $rs['themeFiles']);
plugins/bc-blog/tests/TestCase/Controller/BlogControllerTest.phpに不要フォルダの削除を実行しましたから戻り値が変わりました。

2024-02-19 07:54 UTC, HungDV2022 commented
@ryuring レピューをお願いします。

2024-02-19 07:54 UTC, HungDV2022 commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        SiteConfigFactory::make([
@ryuring こちらを削除しました。確認お願いします。

2024-02-19 07:54 UTC, HungDV2022 commented on plugins/bc-blog/src/View/Helper/BlogHelper.php
> +        $excludes[] = 'Blog';
@ryuring こちらを削除しました。確認お願いします。

2024-02-19 23:23 UTC, ryuring commented on plugins/bc-theme-file/tests/TestCase/Service/Admin/ThemeFilesAdminServiceTest.php
> +        $this->assertCount(11, $rs['themeFiles']);
了解です！

2024-02-19 23:23 UTC, ryuring commented
@HungDV2022 ありがとうございます。マージしますね

2024-02-19 23:23 UTC, merged