fix #3098 【5.1】エディタテンプレート新規登録・編集で必須項目を記入せず、アイコン画像を入れ保存するとエラーが発生する【エディタテンプレート】
baserproject/basercms pull request #3114
Opened 2024-02-14 06:11 UTC by HungDV2022

2024-02-15 03:47 UTC, ryuring requested changes

2024-02-15 03:47 UTC, ryuring commented on plugins/baser-core/src/View/Helper/BcFormHelper.php
> +        if ($fileLinkTag && $linkOptions['delCheck'] && (is_string($value) || (is_object($value) && $value->getError() == UPLOAD_ERR_NO_FILE))) {
@HungDV2022 `empty($value['session_key'])` は削除しないようにしてください、ファイルの一時保存機能が正常動作しなくなるためです

2024-02-15 23:52 UTC, HungDV2022 commented on plugins/baser-core/src/View/Helper/BcFormHelper.php
> +        if ($fileLinkTag && $linkOptions['delCheck'] && (is_string($value) || (is_object($value) && $value->getError() == UPLOAD_ERR_NO_FILE))) {
@ryuring empty($value['session_key'])を追加しました。確認お願いします。

2024-02-16 04:57 UTC, ryuring commented
@HungDV2022 ありがとうございました。マージします。

2024-02-16 04:57 UTC, merged