BlogHelper_getCategoryByName
baserproject/basercms pull request #3177
Opened 2024-02-28 07:53 UTC by thangnnmd

BlogHelper_getCategoryByName

2024-02-28 07:57 UTC, thangnnmd commented
@HungDV2022 please take a look

2024-02-28 11:26 UTC, HungDV2022 commented on plugins/bc-blog/src/View/Helper/BlogHelper.php
> +     * @unitTest
@thangnnmd @noTodo @checked も追加してください、// a thêm cả @noTodo @checked  nữa nhé.

2024-02-28 11:26 UTC, HungDV2022 commented on plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
> +     * @return EntityInterface
@thangnnmd unitestを書いてください。// a viết cả uniitest cho thằng này nữa nhé.

2024-02-29 02:37 UTC, thangnnmd commented on plugins/bc-blog/src/View/Helper/BlogHelper.php
> +     * @unitTest
added

2024-02-29 02:37 UTC, thangnnmd commented on plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
> +     * @return EntityInterface
added

2024-03-04 01:19 UTC, ryuring requested changes
@thangnnmd @HungDV2022 レビューいれました確認お願いします。

2024-03-04 01:19 UTC, ryuring commented on plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
> +        $conditions = array_merge([
@thangnnmd @HungDV2022 配列の階層を変えてしまうと、後方互換が保てずエラーとなってしまいます。
同じ階層のまま、find() の第２引数に入れてください。

2024-03-04 01:19 UTC, ryuring commented on plugins/bc-blog/src/View/Helper/BlogHelper.php
> +     * @notodo
@thangnnmd @HungDV2022 `noTodo` に変更してください

2024-03-04 01:19 UTC, ryuring commented on plugins/bc-blog/src/View/Helper/BlogHelper.php
> +        $blogCategoriesModel =  TableRegistry::getTableLocator()->get('BcBlog.BlogCategories');
@thangnnmd @HungDV2022 `$blogCategoriesModel` でなく、 `$blogCategoriesTable` でお願いします。

2024-03-04 04:08 UTC, thangnnmd commented on plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
> +     * @notodo
changed

2024-03-04 04:08 UTC, thangnnmd commented on plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
> +        $conditions = array_merge([
changed

2024-03-04 04:09 UTC, thangnnmd commented on plugins/bc-blog/src/View/Helper/BlogHelper.php
> +     * @notodo
changed

2024-03-04 04:09 UTC, thangnnmd commented on plugins/bc-blog/src/View/Helper/BlogHelper.php
> +        $blogCategoriesModel =  TableRegistry::getTableLocator()->get('BcBlog.BlogCategories');
changed

2024-03-05 00:20 UTC, HungDV2022 commented
@ryuring もう一度レビューをお願いします。

2024-03-05 05:43 UTC, ryuring commented
@thangnnmd @HungDV2022 Thank you. I will merge this pull request.

2024-03-05 05:44 UTC, merged