fix #3089 【baserCMS5】Twitter→Xに伴うアイコン、文言変更
baserproject/basercms pull request #3185
Opened 2024-02-29 08:30 UTC by kaburk

よろしくお願いします！

2024-02-29 22:29 UTC, ryuring requested changes

2024-02-29 22:29 UTC, ryuring commented on plugins/baser-core/resources/locales/en/baser_core.po
> +msgid "公式TXをフォローする"
@kaburk TXになっちゃってますね

2024-03-01 03:33 UTC, kaburk commented on plugins/baser-core/resources/locales/en/baser_core.po
> +msgid "公式TXをフォローする"
Oh....

2024-03-04 09:32 UTC, kaburk commented
こちらtypoをなおしました、、、再度よろしくお願いします！

2024-03-04 14:47 UTC, merged