fix #2930 テーマ設定のテーマカラーにエラーメッセージ追加
baserproject/basercms pull request #3313
Opened 2024-04-04 16:52 UTC by momofff

管理画面テーマ設定のテーマカラーにてカラーコード以外の任意の文字列も保存できる為、下記の処理を追加いたしました。

1. BcValidation に16進数カラーコード判定のバリデーションを追加
1. 管理画面テーマ設定でテーマカラーにバリデーションを追加

カラーコードのバリデーションには CakePHP の `hexColor` もあるものの6桁以外も判定できるように BcValidation に追加しております。3桁、4桁、6桁、8桁を許容するようにしました。

ご確認よろしくお願いいたします！

2024-04-05 02:48 UTC, ryuring requested changes
@momofff レビュー入れています。よろしくお願いします。

2024-04-05 02:48 UTC, ryuring commented on plugins/bc-theme-config/src/Model/Table/ThemeConfigsTable.php
> +                    'message' => __d('baser_core', 'メインはカラーコードを入力してください。')
@momofff 「メインのカラーコードの形式が間違っています。」にしましょう。他のカラーも同様に修正お願いします。

2024-04-06 00:33 UTC, momofff commented on plugins/bc-theme-config/src/Model/Table/ThemeConfigsTable.php
> +                    'message' => __d('baser_core', 'メインはカラーコードを入力してください。')
@ryuring 
レビューありがとうございます！メッセージ変更しました！

2024-04-06 00:34 UTC, momofff commented
@ryuring 
レビューありがとうございます！変更しましたので確認いただけますと助かります！
お手数ですがよろしくお願いいたします！

2024-04-06 05:35 UTC, merged

2024-04-06 05:35 UTC, ryuring commented
ありがとうございました、マージしました！