fix#3254 【カスタムコンテンツ＞フィールド：5.1】タイプ：ファイルのファイルアップロードサイズ上限、アップロードを許可する拡張子に「マイナス、ひらがな、カタカナ、漢字」を入力し保存が可能
baserproject/basercms pull request #3424
Opened 2024-05-16 01:52 UTC by HungDV2022

2024-05-16 07:12 UTC, HungDV2022 commented
@ryuring レビューをお願いします。

2024-05-17 00:39 UTC, ryuring requested changes

2024-05-17 00:39 UTC, ryuring commented on plugins/bc-custom-content/src/Model/Table/CustomFieldsTable.php
> +                    'rule' => ['checkAlphaNumericWithJson', 'BcCustomContent.email_confirm', "/^[a-z0-9_]+$/"],
@HungDV2022 文字列を許容した時点でルール名が矛盾してしまっています

2024-05-17 00:39 UTC, ryuring commented on plugins/bc-custom-content/src/Model/Table/CustomFieldsTable.php
> +                    'rule' => ['checkAlphaNumericWithJson', 'BcCustomContent.email_confirm', "/^[a-z0-9_]+$/"],
メソッドを分けた方がいいかもしれませんね

2024-05-17 00:39 UTC, ryuring commented on plugins/baser-core/src/Model/Validation/BcValidation.php
> +        $validate = $_POST['validate'];
$_POSTはここで使いたくないですね
他に何か良い方法がないでしょうか？

2024-05-22 03:47 UTC, HungDV2022 commented
@ryuring レビューをお願いします。

2024-05-24 01:14 UTC, ryuring commented
ありがとうございます、マージします！

2024-05-24 01:14 UTC, merged