add unitTest_MailConfigsController_index
baserproject/basercms pull request #3425
Opened 2024-05-16 06:35 UTC by thangnnmd

add unitTest_MailConfigsController_index

2024-05-16 07:06 UTC, HungDV2022 commented on plugins/bc-mail/tests/TestCase/Controller/Admin/MailConfigsControllerTest.php
>  //        $this->Case = $this->getMockForAbstractClass('ControllerTestCase');
@thangnnmd xoá bỏ comment này đi a

2024-05-16 07:06 UTC, HungDV2022 commented on plugins/bc-mail/tests/TestCase/Controller/Admin/MailConfigsControllerTest.php
>  //        unset($this->Case);
@thangnnmd xoá bỏ comment này đi a

2024-05-16 07:08 UTC, thangnnmd commented on plugins/bc-mail/tests/TestCase/Controller/Admin/MailConfigsControllerTest.php
>  //        unset($this->Case);
mấy cái này của bác viết nên anh không xoá ?

2024-05-17 00:40 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Controller/Admin/MailConfigsControllerTest.php
> +        $this->MailConfigsController = new MailConfigsController($this->loginAdmin($this->getRequest()));
@thangnnmd @HungDV2022 この行は使ってないですね

2024-05-17 00:47 UTC, HungDV2022 commented on plugins/bc-mail/tests/TestCase/Controller/Admin/MailConfigsControllerTest.php
> +        $this->MailConfigsController = new MailConfigsController($this->loginAdmin($this->getRequest()));
@thangnnmd 
làm giống thằng này xem nhé a 
https://github.com/baserproject/basercms/pull/3423#discussion_r1604214084

2024-05-19 22:47 UTC, HungDV2022 commented on plugins/bc-mail/tests/TestCase/Controller/Admin/MailConfigsControllerTest.php
> +        $this->MailConfigsController = new MailConfigsController($this->loginAdmin($this->getRequest()));
@ryuring 
こちらを調整しました。確認お願いします。

2024-05-20 01:56 UTC, ryuring requested changes

2024-05-20 01:56 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Controller/Admin/MailConfigsControllerTest.php
> +    public $MailConfigsController;
@thangnnmd @HungDV2022 これは不要ですね

2024-05-20 01:56 UTC, ryuring commented on plugins/bc-mail/tests/TestCase/Controller/Admin/MailConfigsControllerTest.php
> +        unset($this->MailConfigsController);
@thangnnmd @HungDV2022 これは不要ですね

2024-05-22 00:03 UTC, HungDV2022 commented on plugins/bc-mail/tests/TestCase/Controller/Admin/MailConfigsControllerTest.php
> +        unset($this->MailConfigsController);
@ryuring こちらを修正しました。確認お願いします。

2024-05-22 00:03 UTC, HungDV2022 commented on plugins/bc-mail/tests/TestCase/Controller/Admin/MailConfigsControllerTest.php
> +    public $MailConfigsController;
@ryuring こちらを修正しました。確認お願いします。

2024-05-24 01:15 UTC, ryuring commented
ありがとうございます、マージします！

2024-05-24 01:15 UTC, merged