add unitTest_BcFreezeHelper_number
baserproject/basercms pull request #3469
Opened 2024-05-28 14:31 UTC by thangnnmd

add unitTest_BcFreezeHelper_number

2024-05-29 01:03 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/View/Helper/BcFreezeHelperTest.php
> +    }
@thangnnmd a làm thế này thiếu trường hợp, a làm theo thằng  testText nhé.

2024-05-29 07:14 UTC, HungDV2022 commented
@ryuring レビューをお願いします

2024-06-12 00:04 UTC, HungDV2022 commented
@ryuring もう一度レビューをお願いします

2024-06-23 03:06 UTC, ryuring commented
@HungDV2022 @thangnnmd こちら意図が伝わっていないみたいですので再度確認お願いします。分からなかったら聞いてください。

2024-06-24 00:51 UTC, HungDV2022 commented
![スクリーンショット 2024-06-24 9 50 45](https://github.com/baserproject/basercms/assets/110375578/3085ffd8-6bcb-4a14-b15a-10bb1344bcb4)
@ryuring コメントが入っていないからもう一度詳しく教えていただけませんか

2024-06-26 04:48 UTC, ryuring requested changes

2024-06-26 04:49 UTC, ryuring commented
@HungDV2022 ごめんなさい、コメントが pendingのままでした。
こちらになります。
https://github.com/baserproject/basercms/pull/3469#discussion_r1631878248

2024-06-27 02:53 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/View/Helper/BcFreezeHelperTest.php
> +            [true, 'baser.freezed', ['value' => 'BaserCMS2'], '<input type="hidden" name="baser[freezed]" value="BaserCMS2">BaserCMS2'],
@ryuring レビューをお願いします。

2024-06-27 02:56 UTC, ryuring commented
ありがとうございます、マージします！

2024-06-27 02:56 UTC, merged