add unitTest_BcFreezeHelper_password
baserproject/basercms pull request #3470
Opened 2024-05-28 14:32 UTC by thangnnmd

add unitTest_BcFreezeHelper_password

2024-05-29 01:04 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/View/Helper/BcFreezeHelperTest.php
> +    }
@thangnnmd a làm thế này thiếu trường hợp, a làm theo thằng testText nhé.

2024-05-30 11:05 UTC, HungDV2022 commented
@ryuring レビューをお願いします。

2024-06-08 05:20 UTC, ryuring requested changes

2024-06-08 05:20 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcFreezeHelperTest.php
> +            [true, 'baser.freezed', [], '<input type="hidden" name="baser[freezed]" value="BaserCMS">'. h(str_repeat('*', strlen('BaserCMS')))],
@thangnnmd @HungDV2022 期待値を関数で生成するのはやめましょう

2024-06-08 05:21 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcFreezeHelperTest.php
> +            [true, 'baser.freezed', [], '<input type="hidden" name="baser[freezed]" value="BaserCMS">'. h(str_repeat('*', strlen('BaserCMS')))],
@thangnnmd @HungDV2022 https://qiita.com/jnchito/items/eb3cfa9f7db752dcb796

2024-06-12 00:03 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/View/Helper/BcFreezeHelperTest.php
> +            [true, 'baser.freezed', [], '<input type="hidden" name="baser[freezed]" value="BaserCMS">'. h(str_repeat('*', strlen('BaserCMS')))],
@ryuring 期待値を修正しました。確認お願いします。

2024-06-23 03:07 UTC, ryuring commented
ありがとうございます、マージします！

2024-06-23 03:07 UTC, merged