User::isEnableLoginAgentのユニットテスト
baserproject/basercms pull request #3478
Opened 2024-05-31 01:58 UTC by HungDV2022

2024-06-08 05:27 UTC, ryuring requested changes

2024-06-08 05:27 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Model/Entity/UserTest.php
> +        $this->assertTrue($this->User->isEnableLoginAgent($targetUser));
@HungDV2022 @thangnnmd assertFalseのテストを追加してください

2024-06-10 01:36 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/Model/Entity/UserTest.php
> +        $this->assertTrue($this->User->isEnableLoginAgent($targetUser));
@ryuring ユニットテストを追加しました。確認お願いします。

2024-06-10 07:57 UTC, ryuring commented
ありがとうございます、マージします！

2024-06-10 07:57 UTC, merged