User::isEditableUser のユニットテスト
baserproject/basercms pull request #3480
Opened 2024-06-03 03:07 UTC by HungDV2022

2024-06-03 04:46 UTC, HungDV2022 commented
@ryuring レビューをお願いします。

2024-06-08 05:31 UTC, ryuring requested changes

2024-06-08 05:31 UTC, ryuring commented on plugins/baser-core/src/Model/Entity/User.php
> +        $a = $targetUser->isAdmin();
@HungDV2022 これはいらないですよね

2024-06-10 02:50 UTC, HungDV2022 commented on plugins/baser-core/src/Model/Entity/User.php
> +        $a = $targetUser->isAdmin();
@ryuring　すみません。こちらを削除して、テストのパターンを追加しました。 レビューをお願いします。

2024-06-23 03:20 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Model/Entity/UserTest.php
> +        $this->assertTrue($this->User->isEditableUser(UserFactory::make(['id' => 2])->getEntity()));
@HungDV2022 

`Configure::write('BcApp.superUserId', 2)` を何故、記載しているのですか？

`//$isSuper = true, return true` は、間違いで、`!$targetUser->isAdmin()` で true になっている可能性があります。

2024-06-24 02:44 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/Model/Entity/UserTest.php
> +        $this->assertTrue($this->User->isEditableUser(UserFactory::make(['id' => 2])->getEntity()));
@ryuring 分かりやすくように下に移動しました。
　　```
Configure::write('BcApp.superUserId', 2);
        UserFactory::make(['id' => 4])->persist();
        UsersUserGroupFactory::make(['user_id' => 4, 'user_group_id' => 1])->persist();
        $user = $this->getTableLocator()->get('BaserCore.Users')->get(4, contain: 'UserGroups');
```
ログインしている権限はスーパーユーザーではない、かつターゲットユーザーはAdminの場合をテストしています。
確認お願いします。

2024-06-26 05:16 UTC, ryuring commented
ありがとうございます、マージします！

2024-06-26 05:16 UTC, merged