BcBaserHelper::charset
baserproject/basercms pull request #3515
Opened 2024-06-12 02:42 UTC by thangnnmd

2024-06-12 07:07 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
> +        $this->loadFixtureScenario(InitAppScenario::class);
　cái này e nghĩ chỉ cần Factory của thằng site thôi chứ a. @thangnnmd

2024-06-14 00:44 UTC, HungDV2022 commented
@ryuring レビューをお願いします。

2024-06-23 04:02 UTC, ryuring requested changes

2024-06-23 04:02 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
> +            ['<meta charset="Shift-JIS">','Shift-JIS', 'mobile']
@thangnnmd @HungDV2022 Shift-JIS を引き渡すとテストの意味がなくなりますので、utf-8を指定した方がいいですね。

2024-06-26 04:06 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/View/Helper/BcBaserHelperTest.php
> +            ['<meta charset="Shift-JIS">','Shift-JIS', 'mobile']
@ryuring もう一度レビューをお願いします。

2024-06-26 05:00 UTC, ryuring commented
ありがとうございます、マージします！

2024-06-26 05:00 UTC, merged