Cake\ORM\Table::find()の前後にイベントを追加
baserproject/basercms pull request #3547
Opened 2024-06-24 20:38 UTC by kk-uchino

@ryuring 
findの前後にイベントを追加するために、AppTableにCake\ORM\Table::find()をオーバーライドしてイベントを追加しました。
リードレプリカへの接続切り替えなどでの利用を想定しています。

ご確認お願いします。

2024-06-25 02:01 UTC, ryuring commented on plugins/baser-core/src/Model/Table/AppTable.php
> +        $event = $this->dispatchEvent('AppTable.beforeFind', compact('type', 'options'));
@kk-uchino `dispatchLayerEvent` を利用するようにしてください

2024-06-25 02:02 UTC, ryuring commented on plugins/baser-core/src/Model/Table/AppTable.php
> +            if (!empty($event->getData('options'))) {
$event->getResult() も判定に入れるようにしてください

```
($event->getResult() === null || $event->getResult() === true)?
```

2024-06-25 02:04 UTC, ryuring requested changes
@kk-uchino レビュー入れました。
あと、テストも書いてもらえると助かります。

イベントのテストは、 `BcTestCase::entryEventToMock()` というメソッドを利用するとテストがしやすいです。

ファイルの全体検索するとテスト例が出てくると思うので参考にしてください。

2024-06-27 04:43 UTC, ryuring commented
@kk-uchino 今回のリリースに入れたかったので僕の方で、本体の修正とテストの作成を行いました。
https://github.com/baserproject/basercms/pull/3547/commits/aa867859340717868b840f8d2e05e2b138e8dd19
マージします！

2024-06-27 04:43 UTC, merged

2024-06-28 03:22 UTC, kk-uchino commented
@ryuring 
ありがとうございます！