fix #3541 【サブサイト】エイリアスに.(ドット)を設定できない
baserproject/basercms pull request #3564
Opened 2024-07-01 02:07 UTC by HungDV2022

2024-07-01 04:29 UTC, HungDV2022 commented
@ryuring レビューをお願いします。

2024-07-01 23:02 UTC, ryuring requested changes
@HungDV2022 レビュー入れました。よろしくお願いします。

2024-07-01 23:02 UTC, ryuring commented on plugins/baser-core/src/Model/Validation/BcValidation.php
> +    public static function checkSiteAlias($value)
@HungDV2022 `SitesTable` に依存するバリデーションですので、`SitesTable` に定義してください。

2024-07-01 23:02 UTC, ryuring commented on plugins/baser-core/src/Model/Validation/BcValidation.php
> +        $request = Router::getRequest();
@HungDV2022 バリデーションでは、できるだけRequestは使わないようにお願いします。

メソッドの第２引数を定義するとそれからエンティティを取得できます。

例えば、 `$context` という第２引数を定義すると次のような形で参照できます。

`$context['data']['domain_type']`

2024-07-04 02:11 UTC, HungDV2022 commented on plugins/baser-core/src/Model/Validation/BcValidation.php
> +    public static function checkSiteAlias($value)
@ryuring SiteValidation.phpに書きました。確認お願いします。

2024-07-04 02:11 UTC, HungDV2022 commented on plugins/baser-core/src/Model/Validation/BcValidation.php
> +        $request = Router::getRequest();
@ryuring こちらを修正しました。確認お願いします。

2024-07-05 10:13 UTC, ryuring commented
@HungDV2022 ごめんなさい、指示が足りなかったです。以下の仕様でお願いします。

## use_subdomain = 0 の場合
- ドット（.） が利用不可、スラッシュは利用可能
- エラーメッセージ：エイリアスは、半角英数・ハイフン（-）・アンダースコア（_）・ドット（.）・スラッシュ（/）で入力してください。

## use_subdomain = 1、かつ、domain_type = 1 と 2 の場合
- ドット（.） が利用可能、スラッシュは利用不可
- エラーメッセージ：サブドメインや外部ドメインを利用する場合、エイリアスは、半角英数・ハイフン（-）・アンダースコア（_）・ドット（.）で入力してください。

2024-07-08 04:13 UTC, HungDV2022 commented
> @HungDV2022 ごめんなさい、指示が足りなかったです。以下の仕様でお願いします。
> 
> ## use_subdomain = 0 の場合
> * ドット（.） が利用不可、スラッシュは利用可能
> * エラーメッセージ：エイリアスは、半角英数・ハイフン（-）・アンダースコア（_）・ドット（.）・スラッシュ（/）で入力してください。
> 
> ## use_subdomain = 1、かつ、domain_type = 1 と 2 の場合
> * ドット（.） が利用可能、スラッシュは利用不可
> * エラーメッセージ：サブドメインや外部ドメインを利用する場合、エイリアスは、半角英数・ハイフン（-）・アンダースコア（_）・ドット（.）で入力してください。

@ryuring こちらのように修正しました。確認お願いします。

2024-07-09 23:38 UTC, ryuring commented on plugins/baser-core/src/Model/Table/SitesTable.php
> +                $entity->setError('alias', ['checkSiteAlias' => __d('baser_core', 'エイリアスは、半角英数・ハイフン（-）・アンダースコア（_）・ドット（.）・スラッシュ（/）で入力してください。')]);
@HungDV2022 バリデーションメッセージの切り替えは、afterMarshal を使わなくてもバリデーションメソッド内で、エラーメッセージを return すれば対応できるようです。ちょっと試してみてください。
https://book.cakephp.org/5/ja/core-libraries/validation.html#dynamic-validation-error-messages

2024-07-10 05:16 UTC, HungDV2022 commented on plugins/baser-core/src/Model/Table/SitesTable.php
> +                $entity->setError('alias', ['checkSiteAlias' => __d('baser_core', 'エイリアスは、半角英数・ハイフン（-）・アンダースコア（_）・ドット（.）・スラッシュ（/）で入力してください。')]);
@ryuring　SiteValidation.phpに書きました。確認お願いします。

2024-07-15 08:29 UTC, ryuring commented
ありがとうございます、マージします！

2024-07-15 08:29 UTC, merged