BcFormHelper::editor()のユニットテスト
baserproject/basercms pull request #3658
Opened 2024-08-01 00:54 UTC by HungDV2022

2024-08-01 03:18 UTC, HungDV2022 commented
@ryuring レビューをお願いします。

2024-08-04 06:55 UTC, ryuring requested changes

2024-08-04 06:55 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcFormHelperTest.php
> +            ['test', ['editorLanguage' => 'en'], '<span class="bca-textarea"><textarea name="test" style="width:99%;height:540px" id="Test" class="bca-textarea__textarea" rows="5">.*', 'オプションを設定できません
@HungDV2022 editorLanguage を指定した場合の変化をテスト結果に含めてください

2024-08-06 06:41 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/View/Helper/BcFormHelperTest.php
> +            ['test', ['editorLanguage' => 'en'], '<span class="bca-textarea"><textarea name="test" style="width:99%;height:540px" id="Test" class="bca-textarea__textarea" rows="5">.*', 'オプションを設定できません
@ryuring 
[こちらと同じです。](https://github.com/baserproject/basercms/pull/3653#discussion_r1704990700)
'editorLanguage' => 'en'の場合はJSで書き込んでいるの戻り値を確認できないので、他$optionsを変更しました。レビューをお願いします。

2024-08-07 08:37 UTC, ryuring commented
ありがとうございます、マージします！

2024-08-07 08:37 UTC, merged