BcCustomContentControllerEventListener::startup()&setAdminMenu()　のユニットテスト
baserproject/basercms pull request #4026
Opened 2024-11-18 04:35 UTC by HungDV2022

2024-11-18 06:21 UTC, HungDV2022 commented
レビューをお願いします。

2024-11-20 02:52 UTC, ryuring requested changes
@HungDV2022 こちらの件、不要なコードが多くありそうですので、不要なコードを削除して整理してもらえますか？

テストの内容としては、dispatch() して、`Configure::read('BcApp.adminNavigation.Contents')` に期待する値が入ればOKです。

2024-11-20 02:52 UTC, ryuring commented on plugins/bc-custom-content/tests/TestCase/Event/BcCustomContentControllerEventListenerTest.php
> +        $customTable->create([
@HungDV2022 このデータは使われてますか？

2024-11-20 02:52 UTC, ryuring commented on plugins/bc-custom-content/tests/TestCase/Event/BcCustomContentControllerEventListenerTest.php
> +        $this->BcAuthenticationEventListener = new BcCustomContentControllerEventListener();
@HungDV2022 変数名がおかしくないですか？

2024-11-22 00:20 UTC, HungDV2022 commented on plugins/bc-custom-content/tests/TestCase/Event/BcCustomContentControllerEventListenerTest.php
> +        $customTable->create([
@ryuring 
このデータは必要です。削除したらカスタムコンテンツをAdminMenuに反映しませんでした。

2024-11-22 00:20 UTC, HungDV2022 commented on plugins/bc-custom-content/tests/TestCase/Event/BcCustomContentControllerEventListenerTest.php
> +        $this->BcAuthenticationEventListener = new BcCustomContentControllerEventListener();
すみません。修正しました。

2024-11-22 00:20 UTC, merged

2024-11-22 01:50 UTC, ryuring commented
@HungDV2022 ありがとうございました。