URL形式以外の文字が入力できてしまう #4021
baserproject/basercms pull request #4032
Opened 2024-11-19 06:01 UTC by IwasakiRyuichi

https://github.com/baserproject/basercms/issues/4021の対応です。
ご確認お願いします。

2024-11-19 06:23 UTC, ryuring commented on plugins/baser-core/src/Model/Validation/BcValidation.php
> +    public static function urlCheck($value): bool
@IwasakiRyuichi CakePHPの標準の url というバリデーションがあったはずです。Validation クラスを確認してみてください。

2024-11-19 06:50 UTC, IwasakiRyuichi commented
レビュー修正いたしました。

修正内容
・新規で作成した public static function urlCheckを削除しました。
・urlCheckの代わりに、標準のurlを使用しました。

2024-11-20 01:43 UTC, ryuring requested changes

2024-11-20 01:43 UTC, ryuring commented on plugins/bc-theme-config/src/Model/Table/ThemeConfigsTable.php
> +                'rule' => array('url', true),
@IwasakiRyuichi 配列はブレースを使ってください　`[]`

2024-11-20 01:43 UTC, ryuring commented on plugins/bc-theme-config/src/Model/Table/ThemeConfigsTable.php
> +                'provider' => 'bc',
@IwasakiRyuichi 標準の機能を利用する場合、`provider` はなくても動作するはずです。確認お願いします。

2024-11-20 02:49 UTC, IwasakiRyuichi commented
レビューありがとうございます。レビューを受けて下記の修正を行いました。
・`'rule' => array('url', true)`を `'rule' => ['url', true]`に変更しました。
・` 'provider' => 'bc'`の記述を削除しました。

ご確認よろしくお願いします。

2024-11-21 07:06 UTC, ryuring commented
@IwasakiRyuichi ありがとうございます！テストも通りましたのでマージしますね。

2024-11-21 07:06 UTC, merged