テーマをコピーした際にヘルパーの重複エラーが表示される #3978
baserproject/basercms pull request #4102
Opened 2024-12-25 04:50 UTC by IwasakiRyuichi

@ryuring 
大変お待たせしました。コピーしたテーマが正常にフロント画面に表示されるようになりましたのでご確認よろしくお願いします。

2024-12-29 05:51 UTC, ryuring commented
@IwasakiRyuichi changePluginNameSpace や、changePluginClassName と処理がほぼ一緒ですので統合できないか一度考えてみてください。

2025-01-06 04:32 UTC, IwasakiRyuichi commented
@ryuring 
修正完了し、動作も確認できましたが修正内容こちらでよろしいでしょうか？


修正内容
「プラグインのnamespaceを変更する処理とヘルパーのnamespaceを変更する処理」
「プラグインのクラス名とヘルパーのクラス名を変更する処理」
この２つを１つの関数にまとめました。

確認したい点
修正内容を誤って認識したかもしれません。
もしかしたら、「changePluginNameSpace」と「changePluginClassName 」を１つの関数でまとめれないかという意味だったでしょうか？

2025-01-07 03:59 UTC, IwasakiRyuichi commented
@ryuring 

BcUtillに定義していたヘルパーのnamespaceとclassの変更処理を、ThemeServiceの方に移動しました。
ローカルでも正常に動作を確認できています。

2025-01-07 08:34 UTC, ryuring requested changes
@IwasakiRyuichi レビューいれました！

2025-01-07 08:34 UTC, ryuring commented on plugins/baser-core/src/Service/ThemesService.php
> +            $helperClassPath = $pluginPath . 'stc/view/helper' . DS . $newTheme . 'Helper.php';
src が stc になってます。
また、View と Helperはキャメルケースにしないと、linux環境では動作しないです。
（macは、大文字小文字を判別しないので動作します）

2025-01-07 08:53 UTC, IwasakiRyuichi commented on plugins/baser-core/src/Service/ThemesService.php
> +            $helperClassPath = $pluginPath . 'stc/view/helper' . DS . $newTheme . 'Helper.php';
stcの箇所をsrcに修正しました。
ViewとHelperの修正ですが、view⇨View、helper⇨Helperのように修正しましたが、あってますでしょうか？・・

2025-01-08 00:35 UTC, ryuring requested changes

2025-01-08 00:35 UTC, ryuring commented on plugins/baser-core/src/Service/ThemesService.php
> +        $oldTypePath = $pluginPath . 'src/View/Helper' . DS . 'Helper.php';
@IwasakiRyuichi `$oldTypePath` が存在することはないのでこちらは削除で大丈夫です。

2025-01-08 00:35 UTC, ryuring commented on plugins/baser-core/src/Service/ThemesService.php
> +        $oldPath = $pluginPath . 'src/View/Helper' . DS . $oldTheme . 'Helper.php';
@IwasakiRyuichi `/` と `DS` が混在しています。全て `DS` で統一しなければ、`DS` を使っている意味がないです。統一しましょう。

`'src' . DS . 'View' . DS . 'Helper'`

2025-01-08 00:35 UTC, ryuring commented on plugins/baser-core/src/Service/ThemesService.php
> +        if(file_exists($pluginPath . 'src/View/Helper' . DS . 'Helper.php')) {
@IwasakiRyuichi この行の判定は不要です。

2025-01-08 02:24 UTC, IwasakiRyuichi commented on plugins/baser-core/src/Service/ThemesService.php
> +        if(file_exists($pluginPath . 'src/View/Helper' . DS . 'Helper.php')) {
@ryuring 

ファイルパスの見直し、$oldTypePathの削除、373行目の判定削除の修正行いました。

今までDSの概念を分からずにいましたが、DSのおかげで異なるOS間でもファイルパスを適切にできることを知ることができました・・・

2025-01-08 02:35 UTC, merged